name: Publish Package to npmjs
on:
  release:
    types: [published]
jobs:
  test:
    name: "Build and test"
    runs-on: windows-latest
    env:
      NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v3
        with:
          node-version: '20.x'
          registry-url: 'https://registry.npmjs.org'
      - run: npm ci --include prod --include dev
      - run: npx jest
      - run: npx tsc
      - run: npm publish